/*
 * Copyright 2007-2014 Daniel Graf (https://github.com/danielgraf)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * snoCADpdfExportFilter.java
 *
 * Created on 05 July 2008, 15:10
 */

package snocadx;

/**
 *
 * @author  dgraf
 */
public class snoCADpdfExportFilter extends javax.swing.JPanel {
    
    /** Creates new form snoCADpdfExportFilter */
    public snoCADpdfExportFilter() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        colour_group = new javax.swing.ButtonGroup();
        RGB_button = new javax.swing.JRadioButton();
        CMYK_button = new javax.swing.JRadioButton();
        shrink = new javax.swing.JCheckBox();

        colour_group.add(RGB_button);
        RGB_button.setSelected(true);
        RGB_button.setText("RGB");
        RGB_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        RGB_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        RGB_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRGB(evt);
            }
        });

        colour_group.add(CMYK_button);
        CMYK_button.setText("CMYK");
        CMYK_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        CMYK_button.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CMYK_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnCMYK(evt);
            }
        });

        shrink.setText("100mm shrink compensation");
        shrink.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        shrink.setMargin(new java.awt.Insets(0, 0, 0, 0));
        shrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnShrink(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RGB_button)
                    .add(CMYK_button)
                    .add(shrink))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(RGB_button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CMYK_button)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(shrink, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OnShrink(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnShrink

    }//GEN-LAST:event_OnShrink

    private void OnCMYK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnCMYK
    RGB_button.setSelected(false);
    }//GEN-LAST:event_OnCMYK

    private void onRGB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRGB
    CMYK_button.setSelected(true);
    }//GEN-LAST:event_onRGB
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CMYK_button;
    private javax.swing.JRadioButton RGB_button;
    private javax.swing.ButtonGroup colour_group;
    private javax.swing.JCheckBox shrink;
    // End of variables declaration//GEN-END:variables
    
    public boolean getShrink() { return shrink.isSelected() ; }
    public boolean getRGB() { return RGB_button.isSelected(); }
    public boolean getCMYK() { return CMYK_button.isSelected() ;}
}
